import datetime as dt
from turtledemo.penrose import draw

#
current_time = dt.datetime.now()
# print(current_time.year)
# print(current_time.month)
# print(current_time.day)
# print(current_time.hour)
# print(current_time.minute)
# print(current_time.second)
#
# dt1= dt.datetime(2026,3,31,10,15)
# print(dt1)
# dt2= dt.datetime(2026,3,31,10,15,50)
# print(dt2)
# dt3= dt.datetime(2026,3,31,14,15,50, 123456)
# print(dt3)
# dt4= dt.date(2026,3,31)
# print(dt4)

print(current_time)
print(current_time.strftime("%y"))
print(current_time.strftime("%m"))
print(current_time.strftime("%B"))
print(current_time.strftime("%b"))
print(current_time.strftime("%d"))
print(current_time.strftime("%H"))
print(current_time.strftime("%M"))
print(current_time.strftime("%S"))
print(current_time.strftime("%I"))
print(current_time.strftime("%a"))
print(current_time.strftime('%m-%B-%y'))
print(current_time.strftime('%m/%B/%y'))
print(current_time.weekday())
print(current_time.isoweekday())

print(current_time)
print(current_time.replace(year=2027,month=1,day=1))
dt1=dt.date(2021,12,3)
dt2=dt.date(2004,6,15)
tt1= dt.time(11,56,59)
tt2= dt.time(13,34,)
tt3= dt.time(11)
o= dt.datetime.combine(dt1,tt1)
print(o)
o1= dt.datetime.combine(dt2,tt1)
print(o1)
o2=dt.datetime.combine(dt2,tt2)
print(o2)
o3= dt.datetime.combine(dt2,tt3)
print(o3)
